apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: default
  labels:
    app: service
spec:
  type: ClusterIP
  ports:
    - port: 4200
      targetPort: http
      name: http
  selector:
    app: service